In [1]:
import numpy as np
from itertools import permutations
from random import *
import math
import random
import pandas as pd

In [2]:
Planilha = pd.ExcelFile('RotacaoCulturas.xlsx')
TabelaCulturas = pd.read_excel(Planilha,  'Culturas')
TabelaLucratividade = pd.read_excel(Planilha,  'Lucratividade')
TabelaProdutividade = pd.read_excel(Planilha,  'Produtividade')

In [3]:
TabelaCulturas

CulturaIndice  CulturaNome  FamiliaIndice     FamiliaNome  \
0               1       Alface              1     Compositaee   
1               2      Almerao              1     Compositaee   
2               3        Couve              2    Brassicaceae   
3               4     Brocolis              2    Brassicaceae   
4               5      Repolho              2    Brassicaceae   
5               6    CouveFlor              2    Brassicaceae   
6               7    Beterraba              3  Chenopodiaceae   
7               8    Espinafre              3  Chenopodiaceae   
8               9    Abobrinha              4   Cucurbitaceae   
9              10      Moranga              4   Cucurbitaceae   
10             11       Pepino              4   Cucurbitaceae   
11             12     Melancia              4   Cucurbitaceae   
12             13         Alho              5       Liliaceae   
13             14       Cebola              5       Liliaceae   
14             15       Quiabo              6       Malvaceae   
15             16        Milho              7       Gramineae   
16             17        Aveia              7       Gramineae   
17             18       Tomate              8      Solanaceae   
18             19     Pimentao              8      Solanaceae   
19             20       Batata              8      Solanaceae   
20             21      Cenoura              9    Umbelliferae   
21             22     Salsinha              9    Umbelliferae   
22             23  FeijaoVagem             10     Leguminosae   
23             24      Ervilha             10     Leguminosae   
24             25       Feijao             10     Leguminosae   
25             26       Pousio             11          Pousio   

    InicioDaEpocaDePlantio  FimDaEpocaDePlantio InicioDaDemandaDoPlantio  \
0                        1                   12                       12   
1                        1                   12                       11   
2                        3                    6                        6   
3                        2                    6                        9   
4                        2                    6                        8   
5                        3                    6                        8   
6                        3                    7                        5   
7                        2                    7                        7   
8                        8                    3                        1   
9                        9                    1                        2   
10                       1                   12                        4   
11                       8                   10                       11   
12                       3                    4                        9   
13                       3                    6                        8   
14                       8                    3                        8   
15                       8                    4                        1   
16                       3                    5                        -   
17                       1                   12                        5   
18                       1                   12                        5   
19                       8                   10                       11   
20                       3                    7                        8   
21                      10                    3                        4   
22                       8                    4                       12   
23                       3                    4                        6   
24                       8                    9                       11   
25                       1                   12                        -   

   FimDaDemandaDoPlantio  CicloEmDias  CicloEmTi Demanda   Unidade  
0                      3           60          4    3750       Pes  
1                      3          120          5    6000 

In [4]:
L = 16 #Numero maximo de lotes definido no artigo
M = 24 #Numero de periodos de plantio definido no artigo (2 anos)

In [5]:
CulturaIndice = TabelaCulturas.CulturaIndice.to_numpy() #Transformando a Coluna da Planilha em Numpy Array
FamiliaIndice = TabelaCulturas.FamiliaIndice.to_numpy() #Transformando a Coluna da Planilha em Numpy Array
CicloEmTi = TabelaCulturas.CicloEmTi.to_numpy() #Transformando a Coluna da Planilha em Numpy Array

Plantas = CulturaIndice[-1] #Ultimo elemento do indice de Culturas é o número total de Plantas
Familias = FamiliaIndice[-1] #Ultimo elemento do indice de familias é o número total de Famílias
print("Numero de Plantas + Pousio: ", Plantas)
print("Numero de Familias: ", Familias)
vetorPlantasSorteado = np.array(CulturaIndice) #um vetor pra sortear os indices futuramente

Numero de Plantas + Pousio:  26
Numero de Familias:  11


In [6]:
def sorteio(l):
    random.shuffle(l)
    print("Vetor de Plantas sorteado: ", l)
    return l

In [7]:
sorteio(vetorPlantasSorteado) #Realiza um sorteio do vetor de Plantas, ou seja, Escolhe uma permutação e
                                #salva no mesmo vetorPlantasSorteado

Vetor de Plantas sorteado:  [ 8 12  7 23 22 21 17 26  2 14 11 16 20  5 24  4 18 19  3 10  9  1  6 13
 15 25]


array([ 8, 12,  7, 23, 22, 21, 17, 26,  2, 14, 11, 16, 20,  5, 24,  4, 18,
       19,  3, 10,  9,  1,  6, 13, 15, 25], dtype=int64)

In [8]:
def FamiliaConsecutiva(): #Analisa se no vetor sorteado, plantas da mesma familia estao sendo plantadas consecutivamente
                            #Se sim, o vetor é sorteado novamente.
    for i in range(Plantas):
        x2=0
        y2=0
        while (x2==y2): #Começa sendo valido, só sai quando são familias diferentes
            if (i+1==Plantas): #se o vetor terminou
                break
            x = vetorPlantasSorteado[i]  #PlantaAtual
            y = vetorPlantasSorteado[i+1] #ProximaPlanta
            x2 = FamiliaIndice[x-1] #Familia da Planta Atual
            y2 = FamiliaIndice[y-1] #Familia da Próxima Planta
            if (x2==y2):
                if(x2==11): #Se for pousio, pode repetir
                    break
                print("A Planta ", vetorPlantasSorteado[i], "Pertence a Familia", FamiliaIndice[x-1], "E a Planta ", vetorPlantasSorteado[i+1], "Tambem pertence a Familia ", FamiliaIndice[y-1] )
                print("É preciso sortear novamente")
                sorteio(vetorPlantasSorteado) #sorteia
                i=0 #volta pro começo
            

In [9]:
FamiliaConsecutiva()

A Planta  22 Pertence a Familia 9 E a Planta  21 Tambem pertence a Familia  9
É preciso sortear novamente
Vetor de Plantas sorteado:  [ 3 23 15 18 19  8  9 21 24  7  2 12 26  1 11 16  4 17 14 22 13  5 10 20
 25  6]


In [10]:
#Contador de repeticoes, faz um vetor contando a quantidade de vezes que uma planta eh plantada do vetorPlantasSorteado
def contador():
    c=[]
    for i in range(Plantas):
        x=vetorPlantasSorteado[i]
        y=CicloEmTi[x-1]
        print("Planta sorteada %d, Quantidade de vezes que ela é plantada: %d" % (x, y))
        c.append(y)
    contador=np.array(c)
    return contador

In [11]:
contador()

Planta sorteada 3, Quantidade de vezes que ela é plantada: 4
Planta sorteada 23, Quantidade de vezes que ela é plantada: 5
Planta sorteada 15, Quantidade de vezes que ela é plantada: 3
Planta sorteada 18, Quantidade de vezes que ela é plantada: 4
Planta sorteada 19, Quantidade de vezes que ela é plantada: 5
Planta sorteada 8, Quantidade de vezes que ela é plantada: 1
Planta sorteada 9, Quantidade de vezes que ela é plantada: 3
Planta sorteada 21, Quantidade de vezes que ela é plantada: 4
Planta sorteada 24, Quantidade de vezes que ela é plantada: 2
Planta sorteada 7, Quantidade de vezes que ela é plantada: 2
Planta sorteada 2, Quantidade de vezes que ela é plantada: 5
Planta sorteada 12, Quantidade de vezes que ela é plantada: 3
Planta sorteada 26, Quantidade de vezes que ela é plantada: 1
Planta sorteada 1, Quantidade de vezes que ela é plantada: 4
Planta sorteada 11, Quantidade de vezes que ela é plantada: 4
Planta sorteada 16, Quantidade de vezes que ela é plantada: 6
Planta sortead

array([4, 5, 3, 4, 5, 1, 3, 4, 2, 2, 5, 3, 1, 4, 4, 6, 4, 1, 3, 5, 2, 4,
       6, 3, 2, 3], dtype=int64)

In [12]:
#Obtendo o construtor:
def construtor():
    teste = 0 
    while (teste == 0):
        sorteio(vetorPlantasSorteado) #Realiza sorteio
        FamiliaConsecutiva() #Verifica se tem familia Consecutiva no mesmo lote, se tiver sorteia ate nao ter
        c = contador() #Faz o contador do sorteio
        construtor = np.repeat(vetorPlantasSorteado, c)
        if (construtor[M-1] != construtor[M]):  #se o tempo de plantacao cabe na linha
            #print("Vetor Final: ",construtor)
            teste = 1
    return construtor    

In [13]:
construtor()

Vetor de Plantas sorteado:  [ 3 11 23 14 21 25 13 15  9  8  2  7 10 20 16 24  4 17 26 19 12  6 22  5
  1 18]
Planta sorteada 3, Quantidade de vezes que ela é plantada: 4
Planta sorteada 11, Quantidade de vezes que ela é plantada: 4
Planta sorteada 23, Quantidade de vezes que ela é plantada: 5
Planta sorteada 14, Quantidade de vezes que ela é plantada: 3
Planta sorteada 21, Quantidade de vezes que ela é plantada: 4
Planta sorteada 25, Quantidade de vezes que ela é plantada: 2
Planta sorteada 13, Quantidade de vezes que ela é plantada: 2
Planta sorteada 15, Quantidade de vezes que ela é plantada: 3
Planta sorteada 9, Quantidade de vezes que ela é plantada: 3
Planta sorteada 8, Quantidade de vezes que ela é plantada: 1
Planta sorteada 2, Quantidade de vezes que ela é plantada: 5
Planta sorteada 7, Quantidade de vezes que ela é plantada: 2
Planta sorteada 10, Quantidade de vezes que ela é plantada: 6
Planta sorteada 20, Quantidade de vezes que ela é plantada: 3
Planta sorteada 16, Quantida

array([ 3,  3,  3,  3, 11, 11, 11, 11, 23, 23, 23, 23, 23, 14, 14, 14, 21,
       21, 21, 21, 25, 25, 13, 13, 15, 15, 15,  9,  9,  9,  8,  2,  2,  2,
        2,  2,  7,  7, 10, 10, 10, 10, 10, 10, 20, 20, 20, 16, 16, 16, 16,
       16, 16, 24, 24,  4,  4,  4,  4, 17, 26, 19, 19, 19, 19, 19, 12, 12,
       12,  6,  6,  6, 22, 22, 22, 22, 22,  5,  5,  5,  5,  1,  1,  1,  1,
       18, 18, 18, 18], dtype=int64)

In [14]:
#Agora é só repetir em todos os Lotes, de 0 até L
Cult = np.zeros((L, M))
Families = np.zeros((L, M))
constr = construtor()
for i in range(L):
    for j in range(M):
        Cult[i,j]=constr[j]
    constr = construtor()


Vetor de Plantas sorteado:  [20 19  3 17  9  5 12  6 16 25 14  7 11  4 21  1 24 13 22 10  8 23  2 26
 15 18]
A Planta  20 Pertence a Familia 8 E a Planta  19 Tambem pertence a Familia  8
É preciso sortear novamente
Vetor de Plantas sorteado:  [15 20 21 23 19 16 12  1 25 17  9  6  7 10 24 26  2  3  8 18 13  4 11 22
  5 14]
Planta sorteada 15, Quantidade de vezes que ela é plantada: 3
Planta sorteada 20, Quantidade de vezes que ela é plantada: 3
Planta sorteada 21, Quantidade de vezes que ela é plantada: 4
Planta sorteada 23, Quantidade de vezes que ela é plantada: 5
Planta sorteada 19, Quantidade de vezes que ela é plantada: 5
Planta sorteada 16, Quantidade de vezes que ela é plantada: 6
Planta sorteada 12, Quantidade de vezes que ela é plantada: 3
Planta sorteada 1, Quantidade de vezes que ela é plantada: 4
Planta sorteada 25, Quantidade de vezes que ela é plantada: 2
Planta sorteada 17, Quantidade de vezes que ela é plantada: 1
Planta sorteada 9, Quantidade de vezes que ela é plantada

Planta sorteada 22, Quantidade de vezes que ela é plantada: 5
Planta sorteada 16, Quantidade de vezes que ela é plantada: 6
Planta sorteada 12, Quantidade de vezes que ela é plantada: 3
Planta sorteada 19, Quantidade de vezes que ela é plantada: 5
Planta sorteada 11, Quantidade de vezes que ela é plantada: 4
Planta sorteada 24, Quantidade de vezes que ela é plantada: 2
Planta sorteada 4, Quantidade de vezes que ela é plantada: 4
Vetor de Plantas sorteado:  [ 2 17 19 23 21  8  7  9  5 20 24  3 26  4  1 25 22 15 12 10 16 13 11  6
 14 18]
A Planta  8 Pertence a Familia 3 E a Planta  7 Tambem pertence a Familia  3
É preciso sortear novamente
Vetor de Plantas sorteado:  [11  5 19 20  3  1  6  4 15 22  8 13 10 18 24  9  2 12 25 14 21 16  7 23
 26 17]
A Planta  6 Pertence a Familia 2 E a Planta  4 Tambem pertence a Familia  2
É preciso sortear novamente
Vetor de Plantas sorteado:  [ 1 23  2 20 18  8 13 22 10 19 24  4  3  7 16 12  5 15  6 17 26  9 14 25
 21 11]
A Planta  4 Pertence a Familia 2

Vetor de Plantas sorteado:  [ 6  3 19 22  9  1 15 12 13  8 16 17  2 21  7 18 11  4 24  5 25 26 10 20
 14 23]
A Planta  6 Pertence a Familia 2 E a Planta  3 Tambem pertence a Familia  2
É preciso sortear novamente
Vetor de Plantas sorteado:  [ 7  3 17 20 12  5  1 14 18 22 23  2 21 24  9 11  6 19  8 13 16 15  4 10
 25 26]
A Planta  9 Pertence a Familia 4 E a Planta  11 Tambem pertence a Familia  4
É preciso sortear novamente
Vetor de Plantas sorteado:  [ 6  1  9  3 19 16 13 14 26 25 20 15  4 18 11  8  5  7  2 10 23 24 22 21
 12 17]
A Planta  23 Pertence a Familia 10 E a Planta  24 Tambem pertence a Familia  10
É preciso sortear novamente
Vetor de Plantas sorteado:  [22 19 10 24  1  2 26  8 15  6 21 11  3  9 20 25  4  7 17 12 13 18 23 14
 16  5]
Planta sorteada 22, Quantidade de vezes que ela é plantada: 5
Planta sorteada 19, Quantidade de vezes que ela é plantada: 5
Planta sorteada 10, Quantidade de vezes que ela é plantada: 6
Planta sorteada 24, Quantidade de vezes que ela é plantada: 2

In [15]:
Cult = Cult.astype(int)

In [16]:
Cult

array([[13, 13, 11, 11, 11, 11, 24, 24,  1,  1,  1,  1, 21, 21, 21, 21,
        25, 25, 17, 22, 22, 22, 22, 22],
       [19, 19, 19, 19, 19,  8, 20, 20, 20, 22, 22, 22, 22, 22,  5,  5,
         5,  5, 10, 10, 10, 10, 10, 10],
       [ 4,  4,  4,  4, 11, 11, 11, 11,  8,  9,  9,  9, 23, 23, 23, 23,
        23, 13, 13,  2,  2,  2,  2,  2],
       [25, 25, 11, 11, 11, 11, 22, 22, 22, 22, 22, 15, 15, 15, 13, 13,
         6,  6,  6,  7,  7, 12, 12, 12],
       [ 6,  6,  6, 18, 18, 18, 18, 16, 16, 16, 16, 16, 16,  1,  1,  1,
         1,  7,  7, 22, 22, 22, 22, 22],
       [26, 22, 22, 22, 22, 22,  3,  3,  3,  3,  7,  7, 17, 24, 24, 23,
        23, 23, 23, 23,  5,  5,  5,  5],
       [25, 25,  1,  1,  1,  1, 18, 18, 18, 18,  8,  5,  5,  5,  5, 21,
        21, 21, 21, 13, 13, 12, 12, 12],
       [21, 21, 21, 21, 18, 18, 18, 18, 10, 10, 10, 10, 10, 10, 15, 15,
        15,  6,  6,  6,  4,  4,  4,  4],
       [ 9,  9,  9,  5,  5,  5,  5, 19, 19, 19, 19, 19, 21, 21, 21, 21,
        12, 12, 12, 18, 

In [17]:
for i in range(L):
    for j in range(M):
        x=Cult[i,j]
        Families[i,j]=FamiliaIndice[x-1]
        

In [18]:
CultFinal1 = pd.DataFrame(Cult, columns=['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro', 'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'])
CultFinal2 = pd.DataFrame(Families, columns=['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro', 'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'])


In [19]:
#CultFinal.to_excel("CulturaConstruida.xlsx", sheet_name='Plantas', index = None, header=True)

with pd.ExcelWriter('CulturaConstruida.xlsx') as writer:  # doctest: +SKIP
    CultFinal1.to_excel(writer, sheet_name='Plantas', index = None, header=True)
    CultFinal2.to_excel(writer, sheet_name='Familias', index = None, header=True)
