In [1]:
import numpy as np
from itertools import permutations
from random import *
import math
import random

In [2]:
L = 5 #Numero máximo de lotes
print("Lotes L =", L)
M = 10 #Numero de periodos
print("Periodos M =", M)
Plantas = 7 #4 Culturas sendo plantadas
print("Tipos de plantas diferentes =", Plantas)
vetorPlantas = [0,1,2,3,4,5,6]
print("Array das Plantas + Pousio: ", vetorPlantas)

Lotes L = 5
Periodos M = 10
Tipos de plantas diferentes = 7
Array das Plantas + Pousio:  [0, 1, 2, 3, 4, 5, 6]


In [3]:
def sorteio(l):
    random.shuffle(l)
    #print("Vetor de Plantas sorteado: ", l)
    return l

In [4]:
#Contador de repeticoes:
def contador():
    c=[]
    for i in range(Plantas):
        if ((vetorPlantas[i]==0) or (vetorPlantas[i]==1) or (vetorPlantas[i]==2) or (vetorPlantas[i]==3)):
            c.append(2)
        if ((vetorPlantas[i]==4) or (vetorPlantas[i]==5) or (vetorPlantas[i]==6)):
            c.append(4)
    #print("Numero de meses que fica plantado: ",c)
    c2 = np.array(c)
    return c2

In [5]:
#Obtendo o construtor:
def construtor():
    teste = 0 
    while (teste == 0):
        sorteio(vetorPlantas)
        c = contador()
        construtor = np.repeat(vetorPlantas, c)
        if (construtor[M-1] != construtor[M]):  #se o tempo de plantacao cabe na linha
            #print("Vetor Final: ",construtor)
            teste = 1
    return construtor    

In [6]:
#Definindo se um vetor pode ocupar o Lote:
Cult = np.zeros((L, M))
constr = construtor()
for i in range(L):
    for j in range(M):
        Cult[i,j]=constr[j]
    constr = construtor()



In [7]:
print (Cult)

[[4. 4. 4. 4. 0. 0. 1. 1. 3. 3.]
 [1. 1. 6. 6. 6. 6. 4. 4. 4. 4.]
 [5. 5. 5. 5. 3. 3. 2. 2. 1. 1.]
 [2. 2. 0. 0. 3. 3. 4. 4. 4. 4.]
 [6. 6. 6. 6. 2. 2. 0. 0. 1. 1.]]


In [8]:
# TEMPO=2: 1= feijão(Leguminosa), 2= Alface, 3= Brócolis
# TEMPO=4: 4=Espinafre 5= Arroz 6= Soja
# 0 = Pousio 
# (Chutando os nomes)

In [9]:
#BUSCA DA VIZINHANÇA
#Vizinhança = S-1 Linha. Ou seja, a solução achada no método construtor, com uma linha sendo substituida
#Como L = 5, Tem 5 vizinhancas
V1 = Cult
V2 = Cult
V3 = Cult
V4 = Cult
V5 = Cult

In [10]:
constr= construtor()
print(constr)
for j in range(M):
    V1[0,j]= constr[j]

constr= construtor()   
for j in range(M):
    V2[1,j]= constr[j]
    
constr= construtor()
for j in range(M):
    V3[2,j]= constr[j]

constr= construtor()
for j in range(M):
    V4[3,j]= constr[j]

constr= construtor()
print(constr)
for j in range(M):
    V5[4,j]= constr[j]
    
print ("Matriz Construida: \n", Cult)    
print("Vizinho 1 = \n", V1)
print("Vizinho 2 = \n", V2)
print("Vizinho 3 = \n", V3)
print("Vizinho 4 = \n", V4)
print("Vizinho 5 = \n", V5)

[2 2 3 3 6 6 6 6 0 0 4 4 4 4 5 5 5 5 1 1]
[6 6 6 6 3 3 2 2 0 0 4 4 4 4 1 1 5 5 5 5]
Matriz Construida: 
 [[2. 2. 3. 3. 6. 6. 6. 6. 0. 0.]
 [6. 6. 6. 6. 0. 0. 5. 5. 5. 5.]
 [4. 4. 4. 4. 6. 6. 6. 6. 2. 2.]
 [0. 0. 1. 1. 4. 4. 4. 4. 3. 3.]
 [6. 6. 6. 6. 3. 3. 2. 2. 0. 0.]]
Vizinho 1 = 
 [[2. 2. 3. 3. 6. 6. 6. 6. 0. 0.]
 [6. 6. 6. 6. 0. 0. 5. 5. 5. 5.]
 [4. 4. 4. 4. 6. 6. 6. 6. 2. 2.]
 [0. 0. 1. 1. 4. 4. 4. 4. 3. 3.]
 [6. 6. 6. 6. 3. 3. 2. 2. 0. 0.]]
Vizinho 2 = 
 [[2. 2. 3. 3. 6. 6. 6. 6. 0. 0.]
 [6. 6. 6. 6. 0. 0. 5. 5. 5. 5.]
 [4. 4. 4. 4. 6. 6. 6. 6. 2. 2.]
 [0. 0. 1. 1. 4. 4. 4. 4. 3. 3.]
 [6. 6. 6. 6. 3. 3. 2. 2. 0. 0.]]
Vizinho 3 = 
 [[2. 2. 3. 3. 6. 6. 6. 6. 0. 0.]
 [6. 6. 6. 6. 0. 0. 5. 5. 5. 5.]
 [4. 4. 4. 4. 6. 6. 6. 6. 2. 2.]
 [0. 0. 1. 1. 4. 4. 4. 4. 3. 3.]
 [6. 6. 6. 6. 3. 3. 2. 2. 0. 0.]]
Vizinho 4 = 
 [[2. 2. 3. 3. 6. 6. 6. 6. 0. 0.]
 [6. 6. 6. 6. 0. 0. 5. 5. 5. 5.]
 [4. 4. 4. 4. 6. 6. 6. 6. 2. 2.]
 [0. 0. 1. 1. 4. 4. 4. 4. 3. 3.]
 [6. 6. 6. 6. 3. 3. 2. 2. 0. 0.]]
Vizinho 5