In [1]:
import numpy as np
from itertools import permutations
from random import *
import math
import random

In [2]:
L = 5 #Numero máximo de lotes
print("Lotes L =", L)
M = 10 #Numero de periodos
print("Periodos M =", M)
Plantas = 7 #4 Culturas sendo plantadas
print("Tipos de plantas diferentes =", Plantas)
vetorPlantas = [0,1,2,3,4,5,6]
print("Array das Plantas + Pousio: ", vetorPlantas)

Lotes L = 5
Periodos M = 10
Tipos de plantas diferentes = 7
Array das Plantas + Pousio:  [0, 1, 2, 3, 4, 5, 6]


In [3]:
def sorteio(l):
    random.shuffle(l)
    #print("Vetor de Plantas sorteado: ", l)
    return l

In [4]:
#Contador de repeticoes:
def contador():
    c=[]
    for i in range(Plantas):
        if ((vetorPlantas[i]==0) or (vetorPlantas[i]==1) or (vetorPlantas[i]==2) or (vetorPlantas[i]==3)):
            c.append(2)
        if ((vetorPlantas[i]==4) or (vetorPlantas[i]==5) or (vetorPlantas[i]==6)):
            c.append(4)
    #print("Numero de meses que fica plantado: ",c)
    c2 = np.array(c)
    return c2

In [5]:
#Obtendo o construtor:
def construtor():
    teste = 0 
    while (teste == 0):
        sorteio(vetorPlantas)
        c = contador()
        construtor = np.repeat(vetorPlantas, c)
        if (construtor[M-1] != construtor[M]):  #se o tempo de plantacao cabe na linha
            print("Vetor Final: ",construtor)
            teste = 1
    return construtor    

In [6]:
#Definindo se um vetor pode ocupar o Lote:
Cult = np.zeros((L, M))
constr = construtor()
for i in range(L):
    for j in range(M):
        Cult[i,j]=constr[j]
    constr = construtor()



Vetor Final:  [2 2 4 4 4 4 5 5 5 5 0 0 1 1 3 3 6 6 6 6]
Vetor Final:  [5 5 5 5 2 2 4 4 4 4 0 0 3 3 6 6 6 6 1 1]
Vetor Final:  [0 0 1 1 6 6 6 6 2 2 3 3 5 5 5 5 4 4 4 4]
Vetor Final:  [3 3 5 5 5 5 6 6 6 6 4 4 4 4 2 2 0 0 1 1]
Vetor Final:  [0 0 6 6 6 6 4 4 4 4 2 2 1 1 5 5 5 5 3 3]
Vetor Final:  [6 6 6 6 4 4 4 4 1 1 3 3 5 5 5 5 2 2 0 0]


In [7]:
print (Cult)

[[2. 2. 4. 4. 4. 4. 5. 5. 5. 5.]
 [5. 5. 5. 5. 2. 2. 4. 4. 4. 4.]
 [0. 0. 1. 1. 6. 6. 6. 6. 2. 2.]
 [3. 3. 5. 5. 5. 5. 6. 6. 6. 6.]
 [0. 0. 6. 6. 6. 6. 4. 4. 4. 4.]]


In [8]:
# TEMPO=2: 1= feijão(Leguminosa), 2= Alface, 3= Brócolis
# TEMPO=4: 4=Espinafre 5= Arroz 6= Soja
# 0 = Pousio 
# (Chutando os nomes)