In [1]:
import numpy as np
from itertools import permutations
from random import *
import math

In [2]:
L = 5 #Numero máximo de lotes
print("Lotes L =", L)
M = 10 #Numero de periodos
print("Periodos M =", M)
Plantas = 4 #4 Culturas sendo plantadas
print("Tipos de plantas diferentes =", Plantas)
l = np.array(list(permutations(range(1,Plantas+1))))
fat= math.factorial(Plantas) 
print("Fatorial = ", fat)
print("Permutações de Culturas Li = ", l)

Lotes L = 5
Periodos M = 10
Tipos de plantas diferentes = 4
Fatorial =  24
Permutações de Culturas Li =  [[1 2 3 4]
 [1 2 4 3]
 [1 3 2 4]
 [1 3 4 2]
 [1 4 2 3]
 [1 4 3 2]
 [2 1 3 4]
 [2 1 4 3]
 [2 3 1 4]
 [2 3 4 1]
 [2 4 1 3]
 [2 4 3 1]
 [3 1 2 4]
 [3 1 4 2]
 [3 2 1 4]
 [3 2 4 1]
 [3 4 1 2]
 [3 4 2 1]
 [4 1 2 3]
 [4 1 3 2]
 [4 2 1 3]
 [4 2 3 1]
 [4 3 1 2]
 [4 3 2 1]]


In [3]:
#Tempo de Plantio:
t1=t2=t3=2 #feijão(Leguminosa), Alface, Brócolis
t4=4 #Espinafre
t5=3 #Pepino
t6=1 #Alho

In [4]:
for k in range(L): #Laço for no número de Lotes
    print(l[0,...])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [5]:
sorteio = randint(0, fat-1)

In [6]:
print(sorteio)

19


In [7]:
for k in range(L): #Laço for no número de Lotes
    sorteio = randint(0, fat-1) #Sorteia um numero aleatorio
    Cult = (l[sorteio,...])
    print(Cult)

[3 1 2 4]
[3 2 1 4]
[4 3 2 1]
[2 4 3 1]
[4 1 3 2]
