In [26]:
import numpy as np
from itertools import permutations
from random import *
import math

In [27]:
L = 5 #Numero máximo de lotes
print("Lotes L =", L)
M = 10 #Numero de periodos
print("Periodos M =", M)
Plantas = 6 #4 Culturas sendo plantadas
print("Tipos de plantas diferentes =", Plantas)
l = np.array(list(permutations(range(1,Plantas+1))))
fat= math.factorial(Plantas) 
print("Fatorial = ", fat)
print("Permutações de Culturas Li = ", l)

Lotes L = 5
Periodos M = 10
Tipos de plantas diferentes = 6
Fatorial =  720
Permutações de Culturas Li =  [[1 2 3 4 5 6]
 [1 2 3 4 6 5]
 [1 2 3 5 4 6]
 ...
 [6 5 4 2 3 1]
 [6 5 4 3 1 2]
 [6 5 4 3 2 1]]


In [28]:
#Tempo de Plantio:
t1=t2=t3=2 #feijão(Leguminosa), Alface, Brócolis
t4=t5=t6=4 #Espinafre

In [29]:
sorteio = randint(0, fat-1)

In [37]:
print(sorteio)
print(l[sorteio,...])  #Vetor sorteado entre as permutacoes

208
[2 5 4 6 1 3]


In [38]:
Cult = np.zeros((L, M))
print(Cult)
j=0
z=0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
print("Vetor inicialmente sorteado:", l[sorteio,...])    
for k in range(L): #Laço for no número de Lotes(de 0 a 4)
    try: #Tenta o vetor sorteado, se der erro por causa do periodo de tempo, tenta outro
        while(j<M): #enquanto T nao eh 10
            Cult[k,j] = l[sorteio,z] #linha 0 coluna 0 eh o 0,0 do vetor sorteado
            if (Cult[k,j] == 1) or (Cult[k,j] == 2) or (Cult[k,j] == 3): #Se a planta for T= 2, Plantar em 2 periodos de tempo 
                j=j+1;
                Cult[k,j] = l[sorteio,z]
                j=j+1; #andar com o tempo pra proxima iteracao
            if (Cult[k,j] == 4) or (Cult[k,j] == 5) or (Cult[k,j] == 6): #T=4 VEZES
                j=j+1;
                Cult[k,j] = l[sorteio,z]
                j=j+1;
                Cult[k,j] = l[sorteio,z]
                j=j+1;
                Cult[k,j] = l[sorteio,z]
                j=j+1;
            z=z+1 #andar no vetor sorteado
        j=0; #Quando acaba de preencher todo o tempo, volta pro for k=1 e a coluna tem q voltar pro zero novamente
    except: #se o vetor nao coube, deu erro por causa do tempo, sorteia outro vetor novamente
        sorteio = randint(0, fat-1)
        print("Vetor sorteado novamente: ", l[sorteio,...])
        j=0;
        z=0
print(Cult)

Vetor inicialmente sorteado: [6 2 4 3 5 1]
Vetor sorteado novamente:  [5 1 3 6 4 2]
Vetor sorteado novamente:  [5 6 1 2 4 3]
Vetor sorteado novamente:  [5 3 6 1 4 2]
[[6. 6. 6. 6. 2. 2. 4. 2. 2. 2.]
 [4. 4. 4. 4. 3. 3. 5. 5. 5. 5.]
 [1. 1. 6. 1. 1. 1. 4. 4. 4. 4.]
 [5. 5. 5. 5. 1. 1. 3. 3. 6. 6.]
 [5. 5. 5. 5. 6. 6. 6. 6. 1. 1.]]
